import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { ToastProvider } from "@heroui/toast";
import Footer from "@/components/footer";
import RedirectHandler from "@/components/RedirectHandler";
import ClerkProviderWrapper from "@/components/ClerkProviderWrapper";


import Script from 'next/script';




import "./globals.css";
import "./styles/styles.css";
import "./styles/vplayer.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Movies & TV Series",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProviderWrapper>
      <html lang="en" className="light">

        <head>
          <Script
            strategy="afterInteractive"
            src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"
          />
          <Script
            id="gtag-init"
            strategy="afterInteractive"
            dangerouslySetInnerHTML={{
              __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-XXXXXXXXXX', { page_path: window.location.pathname });
            `,
            }}
          />
        </head>


        <body
          className={`${geistSans.variable} antialiased font-[family-name:var(--font-geist-sans),sans-serif]`}
        >
          <RedirectHandler />
          <ToastProvider />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProviderWrapper>
  );
}
