import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { ToastProvider } from "@heroui/toast";
import Footer from "@/components/footer";
import RedirectHandler from "@/components/RedirectHandler";
import ClerkProviderWrapper from "@/components/ClerkProviderWrapper";

import "./globals.css";
import "./styles/styles.css";
import "./styles/vplayer.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Movies & TV Series",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProviderWrapper>
      <html lang="en" className="light">
        <body
          className={`${geistSans.variable} antialiased font-[family-name:var(--font-geist-sans),sans-serif]`}
        >
          <RedirectHandler />
          <ToastProvider />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProviderWrapper>
  );
}
